name: CI

on:
  pull_request:
    brachers: [main, dev]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api }} 
      web: ${{ steps.filter.outputs.web }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            api:
              - 'apps/api/**'
              - 'packages/types/**'
            web:
              - 'apps/web/**'
              - 'packages/types/**'
            
  api-ci:
    needs: changes
    if: ${{ needs.changes.outputs.api == 'true' }}
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: resumeiq
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:7-alpine
        ports: ['6379:6379']
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build shared types
        run: pnpm --filter @resumeiq/types build
      - name: Lint
        run: pnpm --filter @resumeiq/api lint
      - name: Typecheck
        run: pnpn --filter @resumeiq/api typecheck
      - name: Test
        run: pnpm --filter @resumeiq/api test
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/resumeiq
          REDIS_URL: redis://localhost:6379

  web-ci:
    needs: changes
    if: ${{ needs.changes.outputs.web == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build shared types
        run: pnpm --filter @resumeiq/types build
      - name: Lint
        run: pnpm --filter @resumeiq/web lint
      - name: Typecheck
        run: pnpm --filter @resumeiq/web typecheck